title: MESG Guidelines
description: All you need to know to work at MESG
markdown:
  toc:
    includeLevel: [1, 2, 3]
head:
  - - link
    - rel: apple-touch-icon
      sizes: 180x180
      href: "/apple-touch-icon.png"
  - - link
    - rel: icon
      type: image/png
      sizes: 32x32
      href: "/favicon-32x32.png"
  - - link
    - rel: icon
      type: image/png
      sizes: 16x16
      href: "/favicon-16x16.png"
  - - link
    - rel: icon
      href: "/favicon.png"
  - - meta
    - hid: 'og:image:height'
      property: 'og:image:height'
      content: '1257'
  - - meta
    - hid: 'og:image:width'
      property: 'og:image:width'
      content: '2400'
  - - meta
    - hid: 'og:image'
      property: 'og:image'
      content: 'https://about.mesg.com/og-image.jpg'
  - - script
    - src: https://p.trellocdn.com/embed.min.js
themeConfig:
  logo: /logo-light.png
  searchMaxSuggestions: 15
  lastUpdated: true
  repo: mesg-foundation/
  repoLabel: GitHub
  docsRepo: mesg-foundation/about
  docsDir: ./
  docsBranch: master
  editLinks: true
  editLinkText: Help us improve this page!
  sidebar: 'auto'
  sidebarDepth: 6
  displayAllHeaders: true
  nav:
    - text: Categories
      items:
        - text: Communication
          link: /communication/
        - text: Employees
          link: /employees/
        - text: Meeting
          link: /meeting/
        - text: Development
          link: /development/
        - text: User Experience
          link: /ux/
        - text: Marketing
          link: /marketing/
        - text: Partner
          link: /partner/
        - text: Support
          link: /support/